### ISSUE TITLE
Not working in kaggle.

### ISSUE THREAD

**Issue by darkon12** [wandaweb/Wonder3D-Kaggle#1]
Hi,
I've used your notebook till a couple days ago but now cell no. 3 (Create the model with instant-nsr-pl) is not working.
Log is:
/kaggle/working/Wonder3D/instant-nsr-pl
Traceback (most recent call last):
File "/kaggle/working/Wonder3D/instant-nsr-pl/launch.py", line 125, in
main()
File "/kaggle/working/Wonder3D/instant-nsr-pl/launch.py", line 38, in main
import datasets
File "/kaggle/working/Wonder3D/instant-nsr-pl/datasets/init.py", line 16, in
from . import blender, colmap, dtu, ortho
File "/kaggle/working/Wonder3D/instant-nsr-pl/datasets/blender.py", line 14, in
from models.ray_utils import get_ray_directions
File "/kaggle/working/Wonder3D/instant-nsr-pl/models/init.py", line 16, in
from . import nerf, neus, geometry, texture
File "/kaggle/working/Wonder3D/instant-nsr-pl/models/nerf.py", line 9, in
from models.utils import chunk_batch
File "/kaggle/working/Wonder3D/instant-nsr-pl/models/utils.py", line 10, in
import tinycudann as tcnn
File "/opt/conda/lib/python3.10/site-packages/tinycudann/init.py", line 9, in
from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
File "/opt/conda/lib/python3.10/site-packages/tinycudann/modules.py", line 50, in
C = importlib.import_module(f"tinycudann_bindings.{cc}_C")
File "/opt/conda/lib/python3.10/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)

ImportError: /opt/conda/lib/python3.10/site-packages/tinycudann_bindings/_75_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
FileNotFoundError Traceback (most recent call last)
Cell In[13], line 7
5 import os, datetime
6 path = '/kaggle/working/Wonder3D/instant-nsr-pl/exp/mesh-ortho-out'
----> 7 folders = [f for f in os.listdir(path) if os.path.isdir(os.path.join(path, f))]
8 last_folder = max(folders)
9 os.chdir(os.path.join(path, last_folder))

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/Wonder3D/instant-nsr-pl/exp/mesh-ortho-out'

Can you help ?

**Comment by wandaweb** [comment]
Fixed in latest version, along with some other errors.
